version: '3'

networks:
  ipxe-docker:
    driver: bridge
    ipam:
      driver: default

services:

  ipxe-dhcpd:
    image: wastrachan/dhcpd
    container_name: ipxe-dhcpd
    environment:
      - PUID=1111
      - PGID=1112
    volumes:
      - ./dhcp:/config
    restart: unless-stopped
    network_mode: host

  ipxe-tftp:
    build:
      context: ./dockerfile/tftp
      dockerfile: Dockerfile
    image: local/tftp
    container_name: ipxe-tftp
    ports:
      - "69:69/udp"
    volumes:
      - ./tftp:/var/lib/tftpboot
    environment:
      - PUID=0
      - PGID=0
    restart: unless-stopped
    networks:
      - ipxe-docker

  ipxe-iscsi:
    build:
      context: ./dockerfile/iscsi
      dockerfile: Dockerfile
    image: local/iscsi
    container_name: ipxe-iscsi
    privileged: true
    ports:
      - "3260:3260"
    volumes:
      - /etc/target:/etc/target
      - /sys:/sys
      - /dev:/dev
    restart: unless-stopped
    networks:
      - ipxe-docker

  ipxe-http-server:
    image: nginx:latest
    container_name: ipxe-http-server
    ports:
      - "88:80"
    volumes:
      - ./www:/usr/share/nginx/html
    restart: unless-stopped
    networks:
      - ipxe-docker