# docker-compose.yml

services:
  ipxe-dhcpd:
    image: wastrachan/dhcpd
    container_name: ipxe-dhcpd
    environment:
      - PUID=1111
      - PGID=1112
    volumes:
      - ./dhcp:/config
    restart: unless-stopped
    network_mode: host

  tftp-server:
    image: tftp-server
    container_name: tftp-server
    ports:
      - "69:69/udp"
    volumes:
      - ./tftp:/var/lib/tftpboot
    environment:
      - PUID=0
      - PGID=0
    restart: unless-stopped
    network_mode: host

  # iscsi:
  #   image: dreamcat4/iscsi
  #   run:
  #     net: host
  #     device:
  #       - /dev/ietctl
  #     volume:
  #       - /etc/target:/etc/target
  #       - /sys:/sys
  #       - /dev:/dev

  web-server:
    image: nginx:latest
    container_name: web-server
    ports:
      - "88:80"
    volumes:
      - ./www:/usr/share/nginx/html
    restart: unless-stopped
    network_mode: host
